# tasks file
---
- name: install dependencies
  ansible.builtin.apt:
    name: "{{ cacti_spine_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - cacti-spine
    - cacti-spine-dependencies

- name: create (checkout) directory
  ansible.builtin.file:
    path: "{{ cacti_spine_checkout_path | dirname }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - cacti-spine
    - cacti-spine-checkout

- name: checkout repository
  ansible.builtin.git:
    repo: "{{ cacti_spine_git_repo }}"
    dest: "{{ cacti_spine_checkout_path }}"
    version: "{{ cacti_spine_git_version }}"
    force: true
  register: _git_checkout
  tags:
    - configuration
    - cacti-spine
    - cacti-spine-checkout

- name: install  # noqa no-handler
  block:

    - name: build and install
      ansible.builtin.shell: >
        true \
        && ./bootstrap \
        && ./configure {{ cacti_spine_configure_options | join(' ') }} \
        && make -j{{ ansible_processor_cores + 1 }} \
        && make install \
        && chown root:root {{ cacti_spine_install_prefix }}/bin/spine \
        && chmod u+s {{ cacti_spine_install_prefix }}/bin/spine
      args:
        chdir: "{{ cacti_spine_checkout_path }}"
      changed_when: true
      tags:
        - cacti-spine-build-and-install

    - name: cleanup build  # noqa command-instead-of-module
      ansible.builtin.shell: >
        git reset --hard && git clean -d -x -f
      args:
        chdir: "{{ cacti_spine_checkout_path }}"
      changed_when: true
      tags:
        - cacti-spine-cleanup-build

  when: _git_checkout is changed
  tags:
    - configuration
    - cacti-spine

- name: update configuration file
  ansible.builtin.template:
    src: etc/spine.conf.j2
    dest: "{{ cacti_spine_etc_spine_conf_file }}"
    owner: "{{ cacti_spine_etc_spine_conf_user }}"
    group: "{{ cacti_spine_etc_spine_conf_group }}"
    mode: "{{ cacti_spine_etc_spine_conf_mode }}"
  tags:
    - configuration
    - cacti-spine
    - cacti-spine-configuration

- name: verify
  ansible.builtin.command: >
    {{ cacti_spine_install_prefix }}/bin/spine --version
  changed_when: false
  tags:
    - configuration
    - cacti-spine
    - cacti-spine-verify
